farmsList/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from farmsList.extensions import bcrypt
from farmsList.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)

class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

class Email(SurrogatePK, Model):
    __tablename__ = 'emails'
    sender = Column(db.String(80), nullable=False)
    recipients = Column(db.String(2000), nullable=False)
    body = Column(db.String(6250000), nullable=False)
    time_sent = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)

    def __init__(self, sender, recipients, body, **kwargs):
        db.Model.__init__(self, sender=sender, recipients=recipients, body=body, **kwargs)

    def __repr__(self):
        return '<Email(From:{sender};To:{recipient};Body:{body})>'.format(sender=self.sender, recipient=self.recipient, body=self.body)

class User(UserMixin, SurrogatePK, Model):
    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

farmsList/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

farmsList/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template
from flask_mail import Mail

from farmsList.settings import ProdConfig
from farmsList.assets import assets
from farmsList.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
    mail
)
from farmsList import public, user

def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(public.api.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

farmsList/user/__init__.py
'''The user module.'''

from . import views

farmsList/user/views.py
# -*- coding: utf-8 -*-
import os
import json
from sqlalchemy import func
from farmsList.settings import ProdConfig, DevConfig

from flask import Blueprint, render_template, session, request, redirect, url_for, flash
from flask.ext.login import login_required
from farmsList.extensions import mail
from flask_mail import Message

from farmsList.user.models import Email
from farmsList.public.models import Farmland,Parcel
from farmsList.public.forms import NewParcel1Form
from farmsList.utils import flash_errors
from farmsList.database import db

from farmsList.modules.importCheckers import jsonImportChecker
from farmsList.modules.importers import importer

if os.environ.get("FARMSLIST_ENV") == 'prod':
    server = ProdConfig().HTTP_SERVER
else:
    server = DevConfig().HTTP_SERVER

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")

@blueprint.route("/approve/<int:farmlandId>")
def approve(farmlandId):
    farmland = Farmland.query.filter(Farmland.id == farmlandId).all()[0]
    db.session.query(Farmland).filter(Farmland.id == farmlandId).update({"public": True})
    db.session.commit()
    msg = Message("Your property is now published on Acres!", recipients=[farmland.email])
    anchorTagHtml = "<a href=\"http://" + server + "/farmland-details/" + str(farmlandId) + "\">the property listing</a>"
    msg.html = ("<html>"
                    "<body>"
                        "<p>Please, visit " + anchorTagHtml + " on Acres to see how it looks.</p>"
                        "<p>Thanks,<br>"
                            "Acres"
                        "</p>"
                    "</body>"
                "</html>")
    mail.send(msg)
    Email.create(sender=msg.sender,
                recipients=",".join(msg.recipients),
                body=msg.html)
    return redirect(url_for('public.home'))

@blueprint.route("/request-changes/<int:farmlandId>")
def reject(farmlandId):
    farmland = Farmland.query.filter(Farmland.id == farmlandId).all()[0]
    msg = Message("Your property cannot be published on Acres", recipients=[farmland.email])
    msg.html = ("<html>"
                    "<body>"
                        "<p>"
                            "We're sorry, but your property cannot be published on Acres at this time. "
                            "Someone will be reaching out to your with more information."
                        "</p>"
                        "<p>Thanks,<br>"
                            "Acres"
                        "</p>"
                    "</body>"
                "</html>")
    mail.send(msg)
    Email.create(sender=msg.sender,
                    recipients=",".join(msg.recipients),
                    body=msg.html)
    return redirect(url_for('public.home'))

@blueprint.route("/list-farmland", methods=['GET', 'POST'])
def list_farmland():
    form = NewParcel1Form(request.form)
    if form.validate_on_submit():
        address = form.address.data
        water = 0 if form.water.data == '' else form.water.data
        zoning = 'Unknown'
        soil = 'Made land'
        geometry = db.session.query(func.ST_GeomFromGeoJSON(form.geometry.data)).all()[0]
        center = db.session.query(func.ST_GeomFromGeoJSON(form.center.data)).all()[0]
        knownParcel = None
        queryResult = db.session.query(Parcel).filter(func.ST_Contains(Parcel.geom, center)).all()
        if len(queryResult) > 0:
            knownParcel = queryResult[0]
            soil = knownParcel.soil
            zoning = knownParcel.zoning
            if water == 0 and knownParcel.water > 0:
                water = knownParcel.water
        new_parcel = Farmland.create(email=form.email.data,
                        ownerName = form.ownerName.data,
                        address=address,
                        size=form.size.data,
                        hasWater = form.hasWater.data,
                        water=water,
                        developmentPlan=form.developmentPlan.data,
                        monthlyCost=form.monthlyCost.data,
                        geometry=geometry,
                        center=center,
                        zoning=zoning,
                        soil=soil,
                        priorUses=form.knownPriorUses.data,
                        public=True)
        return redirect(url_for('public.home'))
    return render_template("users/list-farmland.html", form=form)

@blueprint.route("/import-parcels", methods=['GET', 'POST'])
def import_parcels():
    if request.method == 'POST':
        userVerified = False
        if 'verified' in request.args:
            userVerified = request.args['verified']
            parcels = session['import-data']
        else:
            parcels = json.loads(request.files['importFile'].read())
        if not userVerified:
            session['import-data'] = parcels
            session.modified = True
        review = False
        if userVerified:
            importer().importParcels(parcels)
            issues = 'No issues! Content imported successfully!'
            session.pop('import-data', None)
        else:
            importChecker = jsonImportChecker()
            issues = importChecker.validateParcels(parcels)
            if issues == 'No issues!':
                issues = importChecker.findUpdates(parcels)
            if issues == 'No issues!':
                importer().importParcels(parcels)
                issues = 'No issues! Content imported successfully!'
                session.pop('import-data', None)
            else:
                review = True
        return render_template("users/import-issues.html", issues=issues, review=review)
    return render_template("users/import-parcels.html")

farmsList/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

farmsList/templates/app-base.html
{% include "head.html" %}
<body ng-app="listApp" class="{% block body_class %}{% endblock %} ng-cloak" id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PC2XRN"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PC2XRN');</script>
<!-- End Google Tag Manager -->
{% block body %}

{% with form=form  %}


{% block content %}{% endblock %}


{% endwith %}



<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}

</body>
</html>

farmsList/templates/footer.html
<!-- Footer -->
<footer>
    <div class="container text-center">
        <p>Made by <a href="http://codeforamerica.com">Code for America</a> in partnership with <a href="http://www.cityofwestsacramento.org/">The City of West Sacramento</a> and <a href="http://sacog.org/">SACOG</a>. Icons by Inna Belenkey and Alberto Elizondo from the Noun Project.</p>

        <ul class="logos">
            <li><img src="../static/public/images/westsac_logo.png" width="100px"></li>
            <li><img src="../static/public/images/cfa_logo.png" width="100px"></li>
            <li><img src="../static/public/images/sacog_logo.png" width="100px"></li>
        </ul>
    </div>
</footer>

farmsList/templates/head.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <title>{% block page_title %} Acres {% endblock %}</title>
  <meta name="Web app to add land parcels by one end and search for land the other" content="{% block meta_description %}{% endblock %}">
  <meta name="West Sacramento Team" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.css' rel='stylesheet' />

  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

  <link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.css' rel='stylesheet' />
  <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-draw/v0.2.2/leaflet.draw.js'></script>

  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
  <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

  <!-- improve ng-cloak functionality -->
  <style type="text/css">.ng-cloak { display:none; }</style>
</head>

farmsList/templates/header.html
<!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Acres</h1>
                        <p class="intro-text">The best way to find urban farmland.</p>

                        <a class="btn btn-home btn-lg btn-browse" href="/find-land" role="button">Browse Properties
                          <span class="fa fa-chevron-right" aria-hidden="true"></span>
                        </a>
                        <!-- <a href="#map" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>  -->
                    </div>
                </div>
            </div>
        </div>
    </header>

farmsList/templates/layout.html
{% include "head.html" %}
<body ng-app="listApp" class="{% block body_class %}{% endblock %} ng-cloak" id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-PC2XRN"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PC2XRN');</script>
<!-- End Google Tag Manager -->
{% with form=form  %}

{% block content %}{% endblock %}

{% endwith %}

{% include "footer.html"%}
<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->

</body>
</html>

farmsList/templates/modal-login.html
<!-- Modal login -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Login</h4>
      </div>
      <div class="modal-body">

          <div class="container-narrow">
            {% if current_user and current_user.is_authenticated() %}
              <!--
              <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a>
              <a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a>
               -->
            {% elif form %}

            <form id="loginForm" method="POST" class="form form-register" action="/" role="login">
              {{ form.hidden_tag() }}
              <div class="form-group">
                {{form.username.label}}
                {{ form.username(placeholder="Username", class_="form-control") }}
              </div>
              <div class="form-group">
                {{form.password.label}}
                {{ form.password(placeholder="Password", class_="form-control") }}
              </div>
              <button type="submit" class="btn btn-default">Log in</button>
            </form>
            {% endif %}
          </div>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal login -->
<div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

    </div>
  </div>
</div>

farmsList/templates/nav-form.html
<div id="nav-form">
  <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{{ url_for('public.home') }}">
                    <i class="fa fa-play-circle"></i>  <span class="light">Acres</span>
                </a>
            </div>
        </div>
        <!-- /.container -->
    </nav>
</div>

farmsList/templates/nav.html
<!-- Navigation -->
  <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                  <i class="fa fa-bars"></i>
              </button>
              <a class="navbar-brand page-scroll" href="#page-top">
                  <i class="fa fa-play-circle"></i>  <span class="light">Acres</span>
              </a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
              <ul class="nav navbar-nav">
                  <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                  <li class="hidden">
                      <a href="#page-top"></a>
                  </li>
                  <li><a class="page-scroll" href="/find-land">Find land</a></li>
                  <li><a class="page-scroll" href="#about">About</a></li>
                  <li><a class="page-scroll" href="{{ url_for('user.list_farmland') }}">List Property</a></li>
              </ul>
          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
  </nav>