farmsList/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from farmsList.extensions import bcrypt
from farmsList.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)

class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

class Email(SurrogatePK, Model):
    __tablename__ = 'emails'
    sender = Column(db.String(80), nullable=False)
    recipients = Column(db.String(2000), nullable=False)
    body = Column(db.String(6250000), nullable=False)
    time_sent = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)

    def __init__(self, sender, recipients, body, **kwargs):
        db.Model.__init__(self, sender=sender, recipients=recipients, body=body, **kwargs)

    def __repr__(self):
        return '<Email(From:{sender};To:{recipient};Body:{body})>'.format(sender=self.sender, recipient=self.recipient, body=self.body)

class User(UserMixin, SurrogatePK, Model):
    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

farmsList/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

farmsList/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template
from flask_mail import Mail

from farmsList.settings import ProdConfig
from farmsList.assets import assets
from farmsList.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
    mail
)
from farmsList import public, user

def create_app(config_object=ProdConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app


def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)
    return None


def register_blueprints(app):
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(public.api.blueprint)
    return None


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

farmsList/user/__init__.py
'''The user module.'''

from . import views

farmsList/user/views.py
# -*- coding: utf-8 -*-
import os
import json
from sqlalchemy import func
from farmsList.settings import ProdConfig, DevConfig

from flask import Blueprint, render_template, session, request, redirect, url_for, flash
from flask.ext.login import login_required
from farmsList.extensions import mail
from flask_mail import Message

from farmsList.user.models import Email
from farmsList.public.models import Farmland,Parcel
from farmsList.public.forms import NewParcel1Form
from farmsList.utils import flash_errors
from farmsList.database import db

from farmsList.modules.importCheckers import jsonImportChecker
from farmsList.modules.importers import importer

if os.environ.get("FARMSLIST_ENV") == 'prod':
    server = ProdConfig().HTTP_SERVER
else:
    server = DevConfig().HTTP_SERVER

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")

@blueprint.route("/approve/<int:farmlandId>")
def approve(farmlandId):
    farmland = Farmland.query.filter(Farmland.id == farmlandId).all()[0]
    db.session.query(Farmland).filter(Farmland.id == farmlandId).update({"public": True})
    db.session.commit()
    msg = Message("Your property is now published on Acres!", recipients=[farmland.email])
    anchorTagHtml = "<a href=\"http://" + server + "/farmland-details/" + str(farmlandId) + "\">the property listing</a>"
    msg.html = ("<html>"
                    "<body>"
                        "<p>Please, visit " + anchorTagHtml + " on Acres to see how it looks.</p>"
                        "<p>Thanks,<br>"
                            "Acres"
                        "</p>"
                    "</body>"
                "</html>")
    mail.send(msg)
    Email.create(sender=msg.sender,
                recipients=",".join(msg.recipients),
                body=msg.html)
    return redirect(url_for('public.home'))

@blueprint.route("/request-changes/<int:farmlandId>")
def reject(farmlandId):
    farmland = Farmland.query.filter(Farmland.id == farmlandId).all()[0]
    msg = Message("Your property cannot be published on Acres", recipients=[farmland.email])
    msg.html = ("<html>"
                    "<body>"
                        "<p>"
                            "We're sorry, but your property cannot be published on Acres at this time. "
                            "Someone will be reaching out to your with more information."
                        "</p>"
                        "<p>Thanks,<br>"
                            "Acres"
                        "</p>"
                    "</body>"
                "</html>")
    mail.send(msg)
    Email.create(sender=msg.sender,
                    recipients=",".join(msg.recipients),
                    body=msg.html)
    return redirect(url_for('public.home'))

@blueprint.route("/list-farmland", methods=['GET', 'POST'])
def list_farmland():
    form = NewParcel1Form(request.form)
    if form.validate_on_submit():
        address = form.address.data
        water = 0 if form.water.data == '' else form.water.data
        zoning = 'Unknown'
        soil = 'Made land'
        geometry = db.session.query(func.ST_GeomFromGeoJSON(form.geometry.data)).all()[0]
        center = db.session.query(func.ST_GeomFromGeoJSON(form.center.data)).all()[0]
        knownParcel = None
        queryResult = db.session.query(Parcel).filter(func.ST_Contains(Parcel.geom, center)).all()
        if len(queryResult) > 0:
            knownParcel = queryResult[0]
            soil = knownParcel.soil
            zoning = knownParcel.zoning
            if water == 0 and knownParcel.water > 0:
                water = knownParcel.water
        new_parcel = Farmland.create(email=form.email.data,
                        ownerName = form.ownerName.data,
                        address=address,
                        size=form.size.data,
                        hasWater = form.hasWater.data,
                        water=water,
                        developmentPlan=form.developmentPlan.data,
                        monthlyCost=form.monthlyCost.data,
                        geometry=geometry,
                        center=center,
                        zoning=zoning,
                        soil=soil,
                        priorUses=form.knownPriorUses.data,
                        public=True)
        return redirect(url_for('public.home'))
    return render_template("users/list-farmland.html", form=form)

@blueprint.route("/import-parcels", methods=['GET', 'POST'])
def import_parcels():
    if request.method == 'POST':
        userVerified = False
        if 'verified' in request.args:
            userVerified = request.args['verified']
            parcels = session['import-data']
        else:
            parcels = json.loads(request.files['importFile'].read())
        if not userVerified:
            session['import-data'] = parcels
            session.modified = True
        review = False
        if userVerified:
            importer().importParcels(parcels)
            issues = 'No issues! Content imported successfully!'
            session.pop('import-data', None)
        else:
            importChecker = jsonImportChecker()
            issues = importChecker.validateParcels(parcels)
            if issues == 'No issues!':
                issues = importChecker.findUpdates(parcels)
            if issues == 'No issues!':
                importer().importParcels(parcels)
                issues = 'No issues! Content imported successfully!'
                session.pop('import-data', None)
            else:
                review = True
        return render_template("users/import-issues.html", issues=issues, review=review)
    return render_template("users/import-parcels.html")

farmsList/templates/users/import-issues.html
{% extends "layout.html" %}

{% include "nav-form.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <pre>Issues: {{ issues }}</pre>
      {% if review %}
      <form method="POST" action="/users/import-parcels?verified=True" role="form">
        <button class="btn btn-primary btn-lg btn-submit" type="submit">Accept Changes</button>
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

farmsList/templates/users/import-parcels.html
{% extends "layout.html" %}

{% include "nav-form.html" %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p></p>
      <p>For formatting the data in your import file and understanding how this tool works, please refere to the <a href="https://docs.google.com/document/d/1PgRqpIJtAka-Af3rePalYEi5SoBJJOXjYgDvHVWrMmc" target="_blank">documentation</a>.</p>
      <p>
        <button id="upload-btn">Select and Upload File</button>
      </p>
      <p id='progress-bar' style="display:none;">Running...</p>
      <p>This will take significant time (a few minutes to a few days, depending on the number of geometries being added).</p>
      <p>Please let this run and check back periodically.</p>
    </div>
    <div class="col-md-12" style="height:100px;">
    </div>
  </div>
</div>
<script type="text/javascript">
  var innerFunction,
  forceApply = function(appliedFunction, frequency, attempts) {
    innerFunction = innerFunction || function() {
      forceApply(appliedFunction, frequency, --attempts);
    }
    if (attempts !==0 && (!attempts || attempts < 0)) {
      attempts = 10;
    }
    if (!frequency || frequency <= 0) {
      frequency = 100;
    }
    try {
      appliedFunction();
    } catch(e) {
      if (attempts > 0) {
        setTimeout(innerFunction, frequency);
      } else {
        throw e;
      }
    }
  },
  initializePage = function() {
    var uploader = new ss.SimpleUpload({
      button: 'upload-btn', // HTML element used as upload button
      url: "{{ url_for('user.import_parcels') }}", // URL of server-side upload handler
      name: 'importFile', // Parameter name of the uploaded file
      multipart: true, // This is required for large files
      onSubmit: function() {
        document.getElementById('progress-bar').style.display = 'block';
      },
      onComplete: function(filename, response) { // Instead of eating the response, actually render the HTML
        if (!response) {
              alert(filename + 'upload failed');
              return false;
        } else {
          document.documentElement.innerHTML = response;
          document.body.className = document.body.className.replace(/\bng-cloak\b/,'');  // We need to make sure the ng-cloak is undone
          return true;
        }
      },
      onError: function(filename, type, status, statusText, response, uploadBtn, size) {
        document.getElementById('progress-bar').style.display = 'none';
        alert('An error occurred: ' + statusText);
      }
    });
  };
  forceApply(initializePage);
</script>
{% endblock %}

farmsList/templates/users/list-farmland.html
{% extends "layout.html" %}

{% include "nav-form.html" %}

{% block content %}
<div class="container" ng-controller="PublishListingsController">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">List a Property</h1>
      <p>Use the <img id="draw-tool-img" src="/static/public/images/draw-tool.png"> tool to draw a shape around the location of the property.</p>
      <leaflet id="list-parcels-map" center="center" layers="layers" width="100%" height="480px"></leaflet>
      <hr>
      <h3>Property Details</h3>
      <form id="editParcelForm" class="form form-register form-horizontal" method="POST" action="" role="form">
        {{ form.hidden_tag() }}
        <div class="form-group">
          <div class="col-sm-2 control-label">{{form.address.label}} {% if form.address.flags.required %}<span class="required">*</span>{% endif %}</div>
          <div class="col-sm-6">
            {{form.address(class_="form-control", **{'ng-model':'parcel.address'})}}
            <span class="help-block"><i>This will also serve as the title of the listing.</i></span>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-2 control-label">
            <label for="newParcelSize">Area</label> <span class="required">*</span>
          </div>
          <div class="col-sm-2">
            <div class="input-group">
              <input type="text" id="newParcelSize" name="size" ng-readonly="true" class="readonly form-control">
              <div class="input-group-addon">acres</div>
            </div>




            <span class="help-block"><i>Auto-calculated based on your drawing.</i></span>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-2 control-label">
            {{form.developmentPlan.label}} {% if form.developmentPlan.flags.required %}<span class="required">*</span>{% endif %}
          </div>
          <div class="col-sm-2">
            <div class="input-group">
              {{form.developmentPlan(placeholder="", class_="form-control")}}
              <div class="input-group-addon">years</div>
            </div>

            </div>
        </div>


        <div class="form-group">
          <div class="col-sm-2 control-label">
            <span class="nowrap">{{form.monthlyCost.label}} {% if form.monthlyCost.flags.required %}<span class="required">*</span>{% endif %}</span>
          </div>
          <div class="col-sm-2">
            <div class="input-group">
              <div class="input-group-addon">$</div>
              {{form.monthlyCost(placeholder="", class_="form-control")}}
              </div>
            </div>
        </div>

        <div class="checkbox has-water" ng-init="parcel.hasWater = false;">   
          <label>    
            {{form.hasWater(class_="form-control form-checkbox", **{'ng-model':'parcel.hasWater'})}} {{form.hasWater.label}}   
          </label>   
        </div>   
   
        <div class="form-group water-meter">   
          <div class="col-sm-2 control-label">{{form.water.label}}</div>   
          <div class="col-xs-2">   
            <div class="input-group">    
              {{form.water(class_="form-control", **{'ng-model':'parcel.water'})}}   
              <div class="input-group-addon">inches</div>    
            </div>   
            </div>   
        </div>

        <div class="form-group">
          <div class="col-sm-2 control-label">
            <span class="nowrap">{{form.knownPriorUses.label}} {% if form.knownPriorUses.flags.required %}<span class="required">*</span>{% endif %}</span>
          </div>
          <div class="col-sm-6">
            {{form.knownPriorUses(placeholder="Warehousing, gas station, etc.", class_="form-control", **{'ng-model':'parcel.knownPriorUses'})}}
          </div>
        </div>

        <hr>
        <h3>Owner Details</h3>
        <div class="form-group">
          <div class="col-sm-2 control-label">{{form.ownerName.label}} {% if form.ownerName.flags.required %}<span class="required">*</span>{% endif %}</div>
          <div class="col-sm-6">{{form.ownerName(class_="form-control", **{'ng-model':'parcel.ownerName'})}}</div>
        </div>
        <div class="form-group">
          <div class="col-sm-2 control-label">{{form.email.label}} {% if form.email.flags.required %}<span class="required">*</span>{% endif %}</div>
          <div class="col-sm-6">{{form.email(class_="form-control", **{'ng-model':'parcel.email'})}}
            <span class="help-block"><i>Your e-mail will not be displayed publicly. It will only be used to send you updates from people interested in leasing your property.</i></span>
          </div>
        </div>
        <input type="text" id="newParcelGeometry" name="geometry" class="ng-hide">
        <input type="text" id="newParcelCenter" name="center" class="ng-hide">
        <div class="form-group parcel-submit">
          <div class="col-sm-10">
            <button class="btn btn-primary btn-lg btn-submit" type="submit" value="Post Parcel">Submit Your Property</button>
            <button class="btn btn-danger btn-lg" type="button" value="Cancel" onclick="document.location.href='/'">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

farmsList/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}

farmsList/templates/users/new_parcel_1.html
{% extends "layout.html" %}

{% include "nav-form.html" %}

{% block content %}
<div class="container" ng-controller="PublishListingsController">
  <div class="row">
    <div class="col-md-12">
      <h1 class="page-header">List a Property</h1>
      <p>Use the <img id="draw-tool-img" src="/static/public/images/draw-tool.png"> tool to draw a shape around the location of the property.</p>
      <leaflet id="list-parcels-map" center="center" layers="layers" width="100%" height="480px"></leaflet>
      <hr>
      <h3>Property Details</h3>
      <form id="editParcelForm" class="form form-register form-horizontal" method="POST" action="" role="form">
        {{ form.hidden_tag() }}
        <div class="form-group">
          <div class="col-sm-2 control-label">{{form.address.label}} {% if form.address.flags.required %}<span class="required">*</span>{% endif %}</div>
          <div class="col-sm-6">
            {{form.address(class_="form-control", **{'ng-model':'parcel.address'})}}
            <span class="help-block"><i>This will also serve as the title of the listing.</i></span>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-2 control-label">
            <label for="newParcelSize">Area</label> <span class="required">*</span>
          </div>
          <div class="col-sm-2">
            <div class="input-group">
              <input type="text" id="newParcelSize" name="size" ng-readonly="true" class="readonly form-control">
              <div class="input-group-addon">acres</div>
            </div>




            <span class="help-block"><i>Auto-calculated based on your drawing.</i></span>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-2 control-label">
            {{form.developmentPlan.label}} {% if form.developmentPlan.flags.required %}<span class="required">*</span>{% endif %}
          </div>
          <div class="col-sm-2">
            <div class="input-group">
              {{form.developmentPlan(placeholder="", class_="form-control")}}
              <div class="input-group-addon">years</div>
            </div>

            </div>
        </div>


        <div class="form-group">
          <div class="col-sm-2 control-label">
            <span class="nowrap">{{form.monthlyCost.label}} {% if form.developmentPlan.flags.required %}<span class="required">*</span>{% endif %}</span>
          </div>
          <div class="col-sm-2">
            <div class="input-group">
              <div class="input-group-addon">$</div>
              {{form.monthlyCost(placeholder="", class_="form-control")}}
              </div>
            </div>
        </div>

        <div class="checkbox has-water" ng-init="parcel.hasWater = false;">
          <label>
            {{form.hasWater(class_="form-control form-checkbox", **{'ng-model':'parcel.hasWater'})}} {{form.hasWater.label}}
          </label>
        </div>

        <div class="form-group water-meter">
          <div class="col-sm-2 control-label">{{form.water.label}}</div>
          <div class="col-xs-2">
            <div class="input-group">
              {{form.water(class_="form-control", **{'ng-model':'parcel.water'})}}
              <div class="input-group-addon">inches</div>
            </div>
            </div>
        </div>

        <hr>
        <h3>Owner Details</h3>
        <div class="form-group">
          <div class="col-sm-2 control-label">{{form.ownerName.label}} {% if form.ownerName.flags.required %}<span class="required">*</span>{% endif %}</div>
          <div class="col-sm-6">{{form.ownerName(class_="form-control", **{'ng-model':'parcel.ownerName'})}}</div>
        </div>
        <div class="form-group">
          <div class="col-sm-2 control-label">{{form.email.label}} {% if form.email.flags.required %}<span class="required">*</span>{% endif %}</div>
          <div class="col-sm-6">{{form.email(class_="form-control", **{'ng-model':'parcel.email'})}}
            <span class="help-block"><i>Your e-mail will not be displayed publicly. It will only be used to send you updates from people interested in leasing your property.</i></span>
          </div>
        </div>
        <input type="text" id="newParcelGeometry" name="geometry" class="ng-hide">
        <input type="text" id="newParcelCenter" name="center" class="ng-hide">
        <hr>
        <p><span class="highlighted"><strong>Please note that property listings are approved by City staff before being published.</strong></span></p>
        <div class="form-group parcel-submit">
          <div class="col-sm-10">
            <button class="btn btn-primary btn-lg btn-submit" type="submit" value="Post Parcel">Submit Your Property</button>
            <button class="btn btn-danger btn-lg" type="button" value="Cancel" onclick="document.location.href='/'">Cancel</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}